name: Build and Push Docker Images

on:
  push:
    branches: [ "master", "main" ]
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG'
      - 'LICENSE.txt'
      - 'docs/**'
      - '.vscode/**'
      - '.gitignore'
      - '.env.example'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service: [appserver, dbaccess, licenseserver, mssql, postgres, smartview]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup Resources (Download Binaries)
        run: |
          chmod +x scripts/setup.sh
          ./scripts/setup.sh ${{ matrix.service }}

      - name: Build Image
        run: |
          chmod +x ${{ matrix.service }}/build.sh
          bash ${{ matrix.service }}/build.sh auto

      - name: Push to Docker Hub
        run: |
          chmod +x ${{ matrix.service }}/push.sh
          bash ${{ matrix.service }}/push.sh
